spring:
  application:
    name: music
  h2:
    console:
      enabled: true
  r2dbc:
    url: r2dbc:h2:mem:///musicdb
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
